# Generated by Django 4.0.4 on 2022-08-24 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='inputFile',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='outputFile',
        ),
    ]
