# Generated by Django 4.0.4 on 2022-09-08 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import judge.models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputFile', models.FileField(upload_to=judge.models.get_testcase_input_upload_path)),
                ('outputFile', models.FileField(upload_to=judge.models.get_testcase_output_upload_path)),
                ('inputPath', models.FilePathField(max_length=255, path='C:\\Users\\pilla\\OJ\\oj\\media')),
                ('outputPath', models.FilePathField(max_length=255, path='C:\\Users\\pilla\\OJ\\oj\\media')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.problem')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.CharField(max_length=255, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('submittedFile', models.FileField(upload_to=judge.models.get_submission_upload_path)),
                ('language', models.CharField(choices=[('cpp', 'C++'), ('java', 'Java'), ('python', 'Python')], default='cpp', max_length=255)),
                ('submittedFilePath', models.FilePathField(max_length=255, path='C:\\Users\\pilla\\OJ\\oj\\media')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
