# Generated by Django 4.0.4 on 2022-09-01 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='problem',
        ),
        migrations.DeleteModel(
            name='Problem',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
        migrations.DeleteModel(
            name='TestCase',
        ),
    ]
