# Generated by Django 4.0.4 on 2022-07-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AddField(
            model_name='submission',
            name='language',
            field=models.CharField(blank=True, choices=[('cpp', 'C++'), ('java', 'Java'), ('python', 'Python')], default='cpp', help_text='Choose Language', max_length=50),
        ),
    ]
