# Generated by Django 4.0.4 on 2022-09-01 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('judge', '0002_remove_submission_problem_remove_testcase_problem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('statement', models.CharField(max_length=500)),
                ('difficulty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputFile', models.FileField(upload_to='')),
                ('outputFile', models.FileField(upload_to='')),
                ('inputPath', models.FilePathField(max_length=255, path='C:\\Users\\pilla\\OJ\\oj\\media')),
                ('outputPath', models.FilePathField(max_length=255, path='C:\\Users\\pilla\\OJ\\oj\\media')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.problem')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.CharField(max_length=255)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('submittedFile', models.FileField(upload_to='')),
                ('language', models.CharField(choices=[('cpp', 'C++'), ('java', 'Java'), ('python', 'Python')], default='cpp', max_length=255)),
                ('submittedFilePath', models.FilePathField(max_length=255, path='C:\\Users\\pilla\\OJ\\oj\\media')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.problem')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
