# Generated by Django 4.0.4 on 2022-07-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0003_alter_testcase_input_alter_testcase_output'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={},
        ),
        migrations.RemoveField(
            model_name='submission',
            name='language',
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission',
            field=models.FilePathField(max_length=255),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='input',
            field=models.FilePathField(max_length=255),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='output',
            field=models.FilePathField(max_length=255),
        ),
    ]
