# Generated by Django 4.0.4 on 2022-09-02 10:04

from django.db import migrations, models
import judge.models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0004_alter_testcase_inputfile_alter_testcase_outputfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submittedFile',
            field=models.FileField(upload_to=judge.models.get_submission_upload_path),
        ),
        migrations.AlterField(
            model_name='submission',
            name='verdict',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
