# Generated by Django 3.2.7 on 2022-07-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0004_alter_submission_options_remove_submission_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submission',
            field=models.TextField(),
        ),
    ]
