# Generated by Django 4.0.4 on 2022-07-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0006_alter_submission_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submission',
            field=models.FilePathField(path='C:\\users\\pilla\\oj\\Submissions'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='input',
            field=models.FilePathField(max_length=255, path='C:\\users\\pilla\\oj\\testcases\\input'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='output',
            field=models.FilePathField(max_length=255, path='C:\\users\\pilla\\oj\\testcases\\output'),
        ),
    ]
