# Generated by Django 4.0.4 on 2022-07-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0007_alter_submission_submission_alter_testcase_input_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='input',
            field=models.FilePathField(max_length=255, path='C:\\users\\pilla\\oj\\oj'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='output',
            field=models.FilePathField(max_length=255, path='C:\\users\\pilla\\oj\\oj'),
        ),
    ]
