# Generated by Django 4.0.4 on 2022-07-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0008_alter_testcase_input_alter_testcase_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='input',
            field=models.FilePathField(max_length=255, path='C:\\users\\pilla\\oj\\oj\\testcases\\input'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='output',
            field=models.FilePathField(max_length=255, path='C:\\users\\pilla\\oj\\oj\\testcases\\output'),
        ),
    ]
