# Generated by Django 4.0.4 on 2022-07-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0009_alter_testcase_input_alter_testcase_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submission',
            field=models.FilePathField(path='C:\\users\\pilla\\oj\\oj\\Submissions'),
        ),
    ]
