# Generated by Django 4.0.4 on 2022-07-04 17:56

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0017_alter_submission_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submission',
            field=models.FilePathField(max_length=255, path=pathlib.PureWindowsPath('C:/Users/pilla/OJ/oj'), recursive=True),
        ),
    ]
