# Generated by Django 3.2.7 on 2022-07-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0021_auto_20220704_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submission',
            field=models.FilePathField(allow_folders=True, max_length=255, path='C:\\users\\pilla\\oj\\judge\\Files'),
        ),
    ]
