# Generated by Django 3.2.7 on 2022-07-04 18:30

from django.db import migrations, models
import judge.models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0023_alter_submission_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submission',
            field=models.FilePathField(max_length=255, path=judge.models.submission_path),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='input',
            field=models.FilePathField(max_length=255),
        ),
    ]
