# Generated by Django 3.2.7 on 2022-07-05 08:38

from django.db import migrations, models
import judge.models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0027_alter_testcase_input_alter_testcase_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submission',
            field=models.FilePathField(allow_folders=True, max_length=255, path=judge.models.submission_path),
        ),
    ]
