# Generated by Django 3.2.7 on 2022-07-07 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0029_alter_submission_submission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-submitted_at']},
        ),
    ]
