# Generated by Django 3.2.7 on 2022-07-01 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_auto_20220701_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='problem',
        ),
        migrations.DeleteModel(
            name='Problem',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
        migrations.DeleteModel(
            name='TestCase',
        ),
    ]
